### ISSUE TITLE
Do not display users' emails

### ISSUE THREAD

**Issue by pastDexter** [mavend/corona-games#13]
Currently we are using email as user identificator in lobby and players list.
It would be better to pass nickname at registration and use it as `playerName`

**Comment by turbaszek** [comment]
As discussed on slack, do we need registration / login? @Bombasarkadian @pastDexter @kujbol

**Comment by Bombasarkadian** [comment]
My opinion is to rollback to the previous "landing" screen:
- You type in your name and proceed to lobby
- If you've already done this in the past you get the lobby instantly
In the lobby we can show a sad, default avatar in a corner with a "notification" that will explain you that once you register you could change your username to something nicer (without random string added) and you could play on different devices.

**Comment by pastDexter** [comment]
https://firebase.google.com/docs/auth/web/anonymous-auth
