### ISSUE TITLE
User is allowed to join the same lobby multiple times

### ISSUE THREAD

**Issue by Bombasarkadian** [mavend/corona-games#16]
![Screenshot 2020-03-29 at 18 09 38](https://user-images.githubusercontent.com/2972266/77854106-75260a00-71e8-11ea-99b7-82cbdc542af4.png)
We should detect that we're already in the game and join this seat

**Comment by Bombasarkadian** [comment]
But while in the room it only shows a single user
![Screenshot 2020-03-29 at 18 10 27](https://user-images.githubusercontent.com/2972266/77854138-b3232e00-71e8-11ea-8c12-0dd00a9ea4fb.png)

**Comment by pastDexter** [comment]
I'll take it
