### ISSUE TITLE
Properly attribute used graphics

### ISSUE THREAD

**Issue by Bombasarkadian** [mavend/corona-games#27]
Big pictures all come from here https://icons8.com/ouch/style/hugo-1
I'm not sure about the small ones (the ones visible in lobby)

**Comment by pastDexter** [comment]
I was going to add that 👍

**Comment by pastDexter** [comment]
small icons comes from  https://icons8.com, but I'm open for changing them, they were just used as palceholders

**Comment by pastDexter** [comment]
![image](https://user-images.githubusercontent.com/1544476/77935484-c0f0b600-72b1-11ea-8574-a8ae4731cbbe.png)
