### ISSUE TITLE
No redirect to room after sign up

### ISSUE THREAD

**Issue by Bombasarkadian** [mavend/corona-games#48]
If you open a room URL and are not logged in, you create an account and are not redirected to room. Instead you end up in lobby, which is an issue if a link was to a private room

**Comment by pastDexter** [comment]
```javascript
<Button ... onClick={() => setLines([]) && ChangePhrase()}>
     {t("board.game.new_phrase")}
</Button>
```
`setSth` functions return nothing (`undefined`) so `ChangePhrase()` is never executed
