### ISSUE TITLE
Still can't leave games sometimes

### ISSUE THREAD

**Issue by Bombasarkadian** [mavend/corona-games#52]
![Screenshot 2020-03-30 at 23 22 16](https://user-images.githubusercontent.com/2972266/77963234-4dfd3480-72dd-11ea-80c5-b6baffba7113.png)

I don't know how to reproduce it exactly, but this game is stuck. I can't start it and I can't leave it

**Comment by Bombasarkadian** [comment]
API returns `Invalid credentials ybL_-OQ-GB` on `/leave`

**Comment by pastDexter** [comment]
We should print more meaningful errors than JSON parse errors 😂

**Comment by pastDexter** [comment]
@Bombasarkadian OK, so it looks like you somehow lost or overwritten your credentials in `localStoarage`. This way you can no longer leave or join the room

**Comment by Bombasarkadian** [comment]
But if I can't play in this one and I can't join a new one then my account is unusable, right? We should have some way to prevent this from happening
