### ISSUE TITLE
Setup Airbrake for your JavaScript application

### ISSUE THREAD

**Issue by pastDexter** [mavend/corona-games#66]
### Install Airbrake in 3 easy steps:

**Step 1:** Add the library
Install via NPM:

```shell
npm install @airbrake/browser
```

We also support installation via <a href="https://github.com/airbrake/airbrake-js/tree/master/packages/browser#installation" class="external-link">yarn</a>.

**Step 2:** Import the library

Include the library via a script tag:

```html
<script src="node_modules/@airbrake/browser/dist/airbrake.iife.js"></script>
```

Alternative library import methods can be found on <a href="https://github.com/airbrake/airbrake-js/tree/master/packages/browser#setup" class="external-link">our GitHub</a>.

**Step 3:** Copy this config snippet to your `app.js` file

(You can find your project ID and API KEY with your [project's settings](https://airbrake.io/projects/265788/edit)):

```js
const airbrake = new Notifier({
  projectId: <Your project ID>,
  projectKey: '<Your project API Key>',
  environment: 'production'
});
```

To test that Airbrake has been installed correctly in your JavaScript project, just open up the JavaScript console in your internet browser and paste in:

```js
window.onerror("TestError: This is a test", "path/to/file.js", 123);
```

### Going further

Visit our <a href="https://github.com/airbrake/airbrake-js/tree/master/packages/browser" class="external-link">official GitHub repo</a> for more info on alternative configurations and advanced options.

**Comment by Bombasarkadian** [comment]
They also have a react way of doing this https://github.com/airbrake/airbrake-js/tree/master/packages/browser/examples/react
Is there any benefit in using one method or the other?
