### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by Bombasarkadian** [mavend/corona-games#74]
That's rather low priority, but react complains in console about some asynchronous task being still executed after component unmonuted
![Screenshot 2020-04-01 at 09 50 57](https://user-images.githubusercontent.com/2972266/78112273-4a150380-73fe-11ea-84ae-8d7054f473db.png)

**Comment by pastDexter** [comment]
I already solved it in GamePage with `cancelled` flag.
I'll extract `usePromise` custom hook, to use in other componets as well 👍
