### ISSUE TITLE
Can't play a game joined on another device

### ISSUE THREAD

**Issue by Bombasarkadian** [mavend/corona-games#75]
If you join a room on one device and then switch to another one you can't continue to play this game.
You can join the room but none of your moves get processed. We must either fix it or disallow joining game from different device

**Comment by pastDexter** [comment]
yep, I''ll fix it when @kujbol PR is merged.
We need to save game token in the Firebase store with users data

**Comment by pastDexter** [comment]
it was a known limitation of using `localStorage`
